/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistempelanggaran;

/**
 *
 * @author ADJI
 */
public class CatatanPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatatanPanel
     */
    public CatatanPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setBackground(new java.awt.Color(0, 172, 74));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("BIZ UDPGothic", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 70, 40));

        jTextPane2.setBackground(new java.awt.Color(217, 217, 217));
        jTextPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jTextPane2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 180, 340, -1));

        jTextPane3.setBackground(new java.awt.Color(217, 217, 217));
        jTextPane3.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(jTextPane3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 340, -1));

        jTextPane4.setBackground(new java.awt.Color(217, 217, 217));
        jTextPane4.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(jTextPane4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 340, -1));

        jTextPane5.setBackground(new java.awt.Color(217, 217, 217));
        jTextPane5.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane5.setViewportView(jTextPane5);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempelanggaran/ImageCatatan.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
