/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistempelanggaran;

/**
 *
 * @author ADJI
 */
public class PelanggaranPanel extends javax.swing.JPanel {

    /**
     * Creates new form PelanggaranPanel
     */
    public PelanggaranPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Tidak membawa buku sesuai jadwal", "Ringan", "05"},
                {"02", "Mengganggu ketenangan KBM", "Ringan ", "05"},
                {"03", "Kurang rasa setia kawan", "Ringan", "05"},
                {"04", "Bertindak tidak senonoh kepada kawan", "Sedang", "20"},
                {"05", "Mencoret dinding, kursi, meja, dan pagar", "Sedang ", "20"},
                {"06", "Mengancam/Mengintimidasi kepada teman atau guru", "Ringan", "10"},
                {"07", "Merokok di Sekolah", "Sedang", "20"},
                {"08", "Bertindak tidak sopan kepada guru/karyawan", "Sedang", "20"},
                {"09", "Merusak sarana dan prasarana sekolah", "Sedang ", "20"},
                {"10", "Mengambil hak orang lain ", "Sedang", "15"},
                {"11", "Berjudi", "Berat", "50"},
                {"12", "Membawa senjata tajam/senjata api", "Berat", "100"},
                {"13", "Berperilaku jorok dan asusila ", "Sedang", "20"},
                {"14", "Tindakan Kriminal", "Berat", "100"},
                {"15", "Hamil", "Berat", "100"}
            },
            new String [] {
                "ID Pelanggaran", "Bentuk Pelanggaran", "Kategori", "Point"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 570, 610));

        jButton1.setBackground(new java.awt.Color(0, 172, 74));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pelanggaran");
        jButton1.setBorder(null);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 80, 20));

        jButton2.setBackground(new java.awt.Color(0, 172, 74));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Siswa");
        jButton2.setBorder(null);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 20));

        jButton3.setBackground(new java.awt.Color(217, 217, 217));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Submit");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 270, 80, 30));

        jTextField1.setBackground(new java.awt.Color(217, 217, 217));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 200, 20));

        jTextField2.setBackground(new java.awt.Color(217, 217, 217));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 152, 200, 20));

        jTextField3.setBackground(new java.awt.Color(217, 217, 217));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 20));

        jTextField4.setBackground(new java.awt.Color(217, 217, 217));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 200, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempelanggaran/ImagePelanggaran.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 33, 1030, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
