/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistempelanggaran;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADJI
 */
public class SiswaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SiswaPanel
     */
    public SiswaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 172, 74));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pelanggaran");
        jButton1.setBorder(null);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 100, 30));

        jButton2.setBackground(new java.awt.Color(0, 172, 74));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Siswa");
        jButton2.setBorder(null);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 50, 30));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Achmad Zhafran Alysyam", "XI RPL 1", "01"},
                {"002", "Adji Surwo Firmansyah", "XI RPL 1", "02"},
                {"003", "Adrian Trinata", "XI RPL 1", "03"},
                {"004", "Ahmad Rangga Alfaris ", "XI RPL 1", "04"},
                {"005", "Anugrah Risqi A.P", "XI RPL 1", "05"},
                {"006", "Ardiyanti", "XI RPL 1", "06"},
                {"007", "Bagus Setyo Hadi", "XI RPL 1", "07"},
                {"008", "Bilal Sanayu Majid", "XI RPL 1", "08"},
                {"009", "Bintang Atsal Faros", "XI RPL 1", "09"},
                {"010", "Brilliana Siti Rahayu", "XI RPL 1", "10"},
                {"011", "Bryan Christopher Wijaya", "XI RPL 1", "11"},
                {"012", "Deva Mahendra Putra", "XI RPL 1", "12"},
                {"013", "Dimas Rahmanda A.", "XI RPL 1", "13"},
                {"014", "Dony Septian Romadhon", "XI RPL 1", "14"},
                {"015", "Eugene Sentosa M.", "XI RPL 1", "15"},
                {"016", "Evandra Kesya Y.P", "XI RPL 1", "16"},
                {"017", "Fadilah Nur Ramadhani", "XI RPL 1", "17"},
                {"018", "Fani Budi Hermawan", "XI RPL 1", "18"},
                {"019", "Farrell Muhammad A.", "XI RPL 1", "19"},
                {"020", "Fitra Maulana", "XI RPL 1", "20"},
                {"021", "Grendy Aditya P.", "XI RPL 1", "21"},
                {"022", "Lakhon Aliansyah M.", "XI RPL 1", "22"},
                {"023", "M. Risky Mubarok", "XI RPL 1", "23"},
                {"024", "M. Luqman Arif C.", "XI RPL 1", "24"},
                {"025", "Moreno Ariel Wibowo", "XI RPL 1", "25"},
                {"026", "M. Faiz Risqullah R.", "XI RPL 1", "26"},
                {"027", "M. Rafli Imansyah", "XI RPL 1", "27"},
                {"028", "Radhit Pribadi Tegar", "XI RPL 1", "28"},
                {"029", "Ridholloh Mustofa", "XI RPL 1", "29"},
                {"030", "Suhail Ahmad Rafif", "XI RPL 1", "30"},
                {"031", "Syahru Dhani R.", "XI RPL 1", "31"},
                {"032", "Vincentcius Rafael S.", "XI RPL 1", "32"},
                {"033", "Yeremi Christian A.", "XI RPL 1", "33"}
            },
            new String [] {
                "ID Siswa", "Nama Siswa", "Kelas", "Nomor Absen"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 720, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempelanggaran/MacBook Pro 14_ - 4 (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
